//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public string AyarAdi { get; set; }
        public string AyarDegeri { get; set; }
        public string InpType { get; set; }
        public string SItems { get; set; }
        public string Kategori { get; set; }
        public string Aciklama { get; set; }
        public string Varsayilanlar { get; set; }
        public int SiraNo { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
