//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BFRFormlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BFRFormlar()
        {
            this.BFRDonemlerForms = new HashSet<BFRDonemlerForm>();
            this.BFRDonemlerFormBirims = new HashSet<BFRDonemlerFormBirim>();
            this.BFRDonemlerFormGirisleris = new HashSet<BFRDonemlerFormGirisleri>();
            this.BFRFormlarBirims = new HashSet<BFRFormlarBirim>();
        }
    
        public int BFRFormID { get; set; }
        public string FormAdi { get; set; }
        public string Aciklama { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaYolu { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BFRDonemlerForm> BFRDonemlerForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BFRDonemlerFormBirim> BFRDonemlerFormBirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BFRDonemlerFormGirisleri> BFRDonemlerFormGirisleris { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BFRFormlarBirim> BFRFormlarBirims { get; set; }
    }
}
