//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Birimler()
        {
            this.BFRDonemlerFormBirims = new HashSet<BFRDonemlerFormBirim>();
            this.BFRDonemlerFormGirisleris = new HashSet<BFRDonemlerFormGirisleri>();
            this.BFRFormlarBirims = new HashSet<BFRFormlarBirim>();
            this.Birimler1 = new HashSet<Birimler>();
            this.BirimMaddeleris = new HashSet<BirimMaddeleri>();
            this.FRDonemlerFormBirims = new HashSet<FRDonemlerFormBirim>();
            this.FRDonemlerFormGirisleris = new HashSet<FRDonemlerFormGirisleri>();
            this.FRFormlarBirims = new HashSet<FRFormlarBirim>();
            this.KullaniciBirimleris = new HashSet<KullaniciBirimleri>();
            this.Kullanicilars = new HashSet<Kullanicilar>();
        }
    
        public int BirimID { get; set; }
        public Nullable<int> UstBirimID { get; set; }
        public string BirimKod { get; set; }
        public string BirimKisaAdi { get; set; }
        public string BirimAdi { get; set; }
        public string Adres { get; set; }
        public bool IsMaddeEklenebilir { get; set; }
        public bool IsFaaliyetEklenebilir { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BFRDonemlerFormBirim> BFRDonemlerFormBirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BFRDonemlerFormGirisleri> BFRDonemlerFormGirisleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BFRFormlarBirim> BFRFormlarBirims { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birimler> Birimler1 { get; set; }
        public virtual Birimler Birimler2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BirimMaddeleri> BirimMaddeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRDonemlerFormBirim> FRDonemlerFormBirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRDonemlerFormGirisleri> FRDonemlerFormGirisleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRFormlarBirim> FRFormlarBirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciBirimleri> KullaniciBirimleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
    }
}
