//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyuruEkleri
    {
        public int DuyuruDosyaEkID { get; set; }
        public int DuyuruID { get; set; }
        public string DosyaEkAdi { get; set; }
        public string DosyaYolu { get; set; }
    
        public virtual Duyurular Duyurular { get; set; }
    }
}
