//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Duyurular()
        {
            this.DuyuruEkleris = new HashSet<DuyuruEkleri>();
        }
    
        public int DuyuruID { get; set; }
        public bool AnaSayfadaGozuksun { get; set; }
        public bool AnaSayfaPopupAc { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string AciklamaHtml { get; set; }
        public Nullable<System.DateTime> YayinSonTarih { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuyuruEkleri> DuyuruEkleris { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
