//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faaliyetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faaliyetler()
        {
            this.FaaliyetlerAys = new HashSet<FaaliyetlerAy>();
            this.FaaliyetlerKaynaks = new HashSet<FaaliyetlerKaynak>();
            this.FaaliyetlerMaddes = new HashSet<FaaliyetlerMadde>();
        }
    
        public int FaaliyetID { get; set; }
        public string FaaliyetKod { get; set; }
        public string FaaliyetAdi { get; set; }
        public string TakipGostergesi { get; set; }
        public bool IsAktif { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaaliyetlerAy> FaaliyetlerAys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaaliyetlerKaynak> FaaliyetlerKaynaks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaaliyetlerMadde> FaaliyetlerMaddes { get; set; }
    }
}
