//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaaliyetlerKaynak
    {
        public int FaaliyetlerKaynakID { get; set; }
        public int FaaliyetID { get; set; }
        public int KaynakID { get; set; }
    
        public virtual Faaliyetler Faaliyetler { get; set; }
        public virtual Kaynaklar Kaynaklar { get; set; }
    }
}
