//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRDonemlerFormGirisleri
    {
        public int FRDonemlerFormGirisID { get; set; }
        public int FRDonemlerFormID { get; set; }
        public int FRFormID { get; set; }
        public int BirimID { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaYolu { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual FRDonemlerForm FRDonemlerForm { get; set; }
        public virtual FRFormlar FRFormlar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
