//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRDonemlerForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FRDonemlerForm()
        {
            this.FRDonemlerFormBirims = new HashSet<FRDonemlerFormBirim>();
            this.FRDonemlerFormGirisleris = new HashSet<FRDonemlerFormGirisleri>();
        }
    
        public int FRDonemlerFormID { get; set; }
        public int FRDonemID { get; set; }
        public int FRFormID { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual FRDonemleri FRDonemleri { get; set; }
        public virtual FRFormlar FRFormlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRDonemlerFormBirim> FRDonemlerFormBirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRDonemlerFormGirisleri> FRDonemlerFormGirisleris { get; set; }
    }
}
