//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRFormlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FRFormlar()
        {
            this.FRDonemlerForms = new HashSet<FRDonemlerForm>();
            this.FRDonemlerFormBirims = new HashSet<FRDonemlerFormBirim>();
            this.FRDonemlerFormGirisleris = new HashSet<FRDonemlerFormGirisleri>();
            this.FRFormlarBirims = new HashSet<FRFormlarBirim>();
        }
    
        public int FRFormID { get; set; }
        public string FormAdi { get; set; }
        public string Aciklama { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaYolu { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRDonemlerForm> FRDonemlerForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRDonemlerFormBirim> FRDonemlerFormBirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRDonemlerFormGirisleri> FRDonemlerFormGirisleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRFormlarBirim> FRFormlarBirims { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
