//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRFormlarBirim
    {
        public int FRFormlarBirimID { get; set; }
        public int FRFormID { get; set; }
        public int BirimID { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual FRFormlar FRFormlar { get; set; }
    }
}
