//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GonderilenMailler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GonderilenMailler()
        {
            this.GonderilenMailEkleris = new HashSet<GonderilenMailEkleri>();
            this.GonderilenMailKullanicilars = new HashSet<GonderilenMailKullanicilar>();
        }
    
        public int GonderilenMailID { get; set; }
        public Nullable<int> MesajID { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Konu { get; set; }
        public string Aciklama { get; set; }
        public string AciklamaHtml { get; set; }
        public bool Gonderildi { get; set; }
        public string HataMesaji { get; set; }
        public bool Silindi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailEkleri> GonderilenMailEkleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailKullanicilar> GonderilenMailKullanicilars { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Mesajlar Mesajlar { get; set; }
    }
}
