//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GonderilenMailKullanicilar
    {
        public int GonderilenMailKisiID { get; set; }
        public int GonderilenMailID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string Email { get; set; }
    
        public virtual GonderilenMailler GonderilenMailler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
