//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTBirimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GTBirimler()
        {
            this.GTBirimHesapKodlaris = new HashSet<GTBirimHesapKodlari>();
            this.GTBirimHesapNumaralaris = new HashSet<GTBirimHesapNumaralari>();
            this.GTVeriGirisis = new HashSet<GTVeriGirisi>();
            this.KullaniciGTHesapKodlaris = new HashSet<KullaniciGTHesapKodlari>();
            this.KullaniciGTHesapNumaralaris = new HashSet<KullaniciGTHesapNumaralari>();
        }
    
        public int GTBirimID { get; set; }
        public string BirimKod { get; set; }
        public string BirimAdi { get; set; }
        public bool IsAktif { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTBirimHesapKodlari> GTBirimHesapKodlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTBirimHesapNumaralari> GTBirimHesapNumaralaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTVeriGirisi> GTVeriGirisis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciGTHesapKodlari> KullaniciGTHesapKodlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciGTHesapNumaralari> KullaniciGTHesapNumaralaris { get; set; }
    }
}
