//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTBirimHesapNumaralari
    {
        public int GTBirimHesapNoID { get; set; }
        public int GTBirimID { get; set; }
        public int GTHesapNoID { get; set; }
    
        public virtual GTBirimler GTBirimler { get; set; }
        public virtual GTHesapNumaralari GTHesapNumaralari { get; set; }
    }
}
