//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTHesapKodlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GTHesapKodlari()
        {
            this.GTBirimHesapKodlaris = new HashSet<GTBirimHesapKodlari>();
            this.GTHesapKodlariGelirNitelikleris = new HashSet<GTHesapKodlariGelirNitelikleri>();
            this.GTVerigirisiDetays = new HashSet<GTVerigirisiDetay>();
            this.KullaniciGTHesapKodlaris = new HashSet<KullaniciGTHesapKodlari>();
        }
    
        public int GTHesapKodID { get; set; }
        public string HesapKod { get; set; }
        public string HesapKodAdi { get; set; }
        public bool IsAktif { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTBirimHesapKodlari> GTBirimHesapKodlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTHesapKodlariGelirNitelikleri> GTHesapKodlariGelirNitelikleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTVerigirisiDetay> GTVerigirisiDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciGTHesapKodlari> KullaniciGTHesapKodlaris { get; set; }
    }
}
