//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTHesapKodlariGelirNitelikleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GTHesapKodlariGelirNitelikleri()
        {
            this.GTVerigirisiDetays = new HashSet<GTVerigirisiDetay>();
        }
    
        public int GTHesapKodlariGelirNiteligiID { get; set; }
        public int GTHesapKodID { get; set; }
        public string GelirNiteligiAdi { get; set; }
    
        public virtual GTHesapKodlari GTHesapKodlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTVerigirisiDetay> GTVerigirisiDetays { get; set; }
    }
}
