//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTVergiKimlikNumaralari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GTVergiKimlikNumaralari()
        {
            this.GTVerigirisiDetays = new HashSet<GTVerigirisiDetay>();
        }
    
        public int GTVergiKimlikNoID { get; set; }
        public string VergiKimlikNo { get; set; }
        public string AdSoyad { get; set; }
        public bool IsAktif { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTVerigirisiDetay> GTVerigirisiDetays { get; set; }
    }
}
