//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTVeriGirisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GTVeriGirisi()
        {
            this.GTVerigirisiDetays = new HashSet<GTVerigirisiDetay>();
        }
    
        public int GTVeriGirisiID { get; set; }
        public int GTDonemID { get; set; }
        public int GTHesapNoID { get; set; }
        public System.DateTime AktarimTarihi { get; set; }
        public decimal GelenTutar { get; set; }
        public int GTBirimID { get; set; }
        public int GTVeriGirisDurumID { get; set; }
        public int OnayYapanID { get; set; }
        public System.DateTime OnayTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual GTBirimler GTBirimler { get; set; }
        public virtual GTDonemleri GTDonemleri { get; set; }
        public virtual GTHesapNumaralari GTHesapNumaralari { get; set; }
        public virtual GTVeriGirisDurumlari GTVeriGirisDurumlari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GTVerigirisiDetay> GTVerigirisiDetays { get; set; }
    }
}
