//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTVerigirisiDetay
    {
        public int GTVeriGirisDetayID { get; set; }
        public int GTVeriGirisID { get; set; }
        public int GTHesapKodID { get; set; }
        public int GTHesapKodlariGelirNiteligiID { get; set; }
        public decimal Tutar { get; set; }
        public Nullable<int> GTVergiKimlikNoID { get; set; }
        public string Aciklama { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual GTHesapKodlari GTHesapKodlari { get; set; }
        public virtual GTHesapKodlariGelirNitelikleri GTHesapKodlariGelirNitelikleri { get; set; }
        public virtual GTVergiKimlikNumaralari GTVergiKimlikNumaralari { get; set; }
        public virtual GTVeriGirisi GTVeriGirisi { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
