//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gunler
    {
        public int GunID { get; set; }
        public int GunKodu { get; set; }
        public string GunAdi { get; set; }
        public string GunKisaAdi { get; set; }
        public bool IsHaftaIci { get; set; }
    }
}
