//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullanicilarLog
    {
        public int KullaniciID { get; set; }
        public int YetkiGrupID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> BirimID { get; set; }
        public Nullable<int> UnvanID { get; set; }
        public string Tel { get; set; }
        public string EMail { get; set; }
        public string ResimAdi { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public bool SifresiniDegistirsin { get; set; }
        public bool IsActiveDirectoryUser { get; set; }
        public bool IsAdmin { get; set; }
        public string Aciklama { get; set; }
        public string ParolaSifirlamaKodu { get; set; }
        public Nullable<System.DateTime> ParolaSifirlamGecerlilikTarihi { get; set; }
        public bool FixedHeader { get; set; }
        public bool FixedSidebar { get; set; }
        public bool ScrollSidebar { get; set; }
        public bool RightSidebar { get; set; }
        public bool CustomNavigation { get; set; }
        public bool ToggledNavigation { get; set; }
        public bool BoxedOrFullWidth { get; set; }
        public string ThemeName { get; set; }
        public string BackgroundImage { get; set; }
        public bool IsAktif { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> LastLogonDate { get; set; }
        public string LastLogonIP { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemYapanIP { get; set; }
    }
}
