//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaddelerEslestirilenTurler
    {
        public int MaddelerEslestirilenTurID { get; set; }
        public int MaddeID { get; set; }
        public int MaddeTurID { get; set; }
    
        public virtual Maddeler Maddeler { get; set; }
        public virtual MaddeTurleri MaddeTurleri { get; set; }
    }
}
