//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaddeYilSonuDegerHesaplamaTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaddeYilSonuDegerHesaplamaTipleri()
        {
            this.Maddelers = new HashSet<Maddeler>();
            this.VASurecleriMaddes = new HashSet<VASurecleriMadde>();
        }
    
        public int MaddeYilSonuDegerHesaplamaTipID { get; set; }
        public string YilSonuDegerHesaplamaAdi { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maddeler> Maddelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMadde> VASurecleriMaddes { get; set; }
    }
}
