//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaddelerVeriGirisDonemleri
    {
        public int MaddelerVeriGirisAyID { get; set; }
        public int MaddeID { get; set; }
        public int VACokluVeriDonemID { get; set; }
        public bool IsDosyaYuklensin { get; set; }
    
        public virtual Maddeler Maddeler { get; set; }
        public virtual VACokluVeriDonemleri VACokluVeriDonemleri { get; set; }
    }
}
