//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaddeTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaddeTurleri()
        {
            this.Maddelers = new HashSet<Maddeler>();
            this.MaddelerEslestirilenTurlers = new HashSet<MaddelerEslestirilenTurler>();
            this.MaddeTurleriVeriGirisDonemleris = new HashSet<MaddeTurleriVeriGirisDonemleri>();
            this.VASurecleriMaddes = new HashSet<VASurecleriMadde>();
            this.VASurecleriMaddeTurs = new HashSet<VASurecleriMaddeTur>();
        }
    
        public int MaddeTurID { get; set; }
        public bool IsPlanlananDegerOlacak { get; set; }
        public bool IsPlanlananDegerOlacakGelecekYil { get; set; }
        public bool IsKanitDosyasiYuklemekZorunlu { get; set; }
        public bool IsVeriGirisDonemleriMaddeTurundenKopyalansin { get; set; }
        public string MaddeTurAdi { get; set; }
        public bool IsAktif { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maddeler> Maddelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaddelerEslestirilenTurler> MaddelerEslestirilenTurlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaddeTurleriVeriGirisDonemleri> MaddeTurleriVeriGirisDonemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMadde> VASurecleriMaddes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeTur> VASurecleriMaddeTurs { get; set; }
    }
}
