//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maddeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maddeler()
        {
            this.BirimMaddeleris = new HashSet<BirimMaddeleri>();
            this.FaaliyetlerMaddes = new HashSet<FaaliyetlerMadde>();
            this.Maddeler1 = new HashSet<Maddeler>();
            this.MaddelerEslestirilenTurlers = new HashSet<MaddelerEslestirilenTurler>();
            this.MaddelerVeriGirisDonemleris = new HashSet<MaddelerVeriGirisDonemleri>();
            this.MaddelerFormulEslesenMaddelers = new HashSet<MaddelerFormulEslesenMaddeler>();
            this.MaddelerFormulEslesenMaddelers1 = new HashSet<MaddelerFormulEslesenMaddeler>();
            this.RaporTipleriSecilenMaddelers = new HashSet<RaporTipleriSecilenMaddeler>();
            this.VASurecleriMaddes = new HashSet<VASurecleriMadde>();
        }
    
        public int MaddeID { get; set; }
        public Nullable<int> UstMaddeID { get; set; }
        public Nullable<int> MaddeTurID { get; set; }
        public string MaddeKod { get; set; }
        public string MaddeAdi { get; set; }
        public string Aciklama { get; set; }
        public int VeriGirisSekliID { get; set; }
        public string HesaplamaFormulu { get; set; }
        public Nullable<int> MaddeYilSonuDegerHesaplamaTipID { get; set; }
        public Nullable<int> VeriTipID { get; set; }
        public bool IsAktif { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BirimMaddeleri> BirimMaddeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaaliyetlerMadde> FaaliyetlerMaddes { get; set; }
        public virtual MaddeTurleri MaddeTurleri { get; set; }
        public virtual MaddeYilSonuDegerHesaplamaTipleri MaddeYilSonuDegerHesaplamaTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maddeler> Maddeler1 { get; set; }
        public virtual Maddeler Maddeler2 { get; set; }
        public virtual VeriGirisSekilleri VeriGirisSekilleri { get; set; }
        public virtual VeriTipleri VeriTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaddelerEslestirilenTurler> MaddelerEslestirilenTurlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaddelerVeriGirisDonemleri> MaddelerVeriGirisDonemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaddelerFormulEslesenMaddeler> MaddelerFormulEslesenMaddelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaddelerFormulEslesenMaddeler> MaddelerFormulEslesenMaddelers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaporTipleriSecilenMaddeler> RaporTipleriSecilenMaddelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMadde> VASurecleriMaddes { get; set; }
    }
}
