//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaddeTurleriVeriGirisDonemleri
    {
        public int MaddeTurleriVeriGirisDonemID { get; set; }
        public int MaddeTurID { get; set; }
        public int VACokluVeriDonemID { get; set; }
        public bool IsDosyaYuklensin { get; set; }
    
        public virtual MaddeTurleri MaddeTurleri { get; set; }
        public virtual VACokluVeriDonemleri VACokluVeriDonemleri { get; set; }
    }
}
