//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSablonTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MailSablonTipleri()
        {
            this.MailSablonlaris = new HashSet<MailSablonlari>();
        }
    
        public int MailSablonTipID { get; set; }
        public string SablonTipAdi { get; set; }
        public bool SistemMaili { get; set; }
        public string Parametreler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailSablonlari> MailSablonlaris { get; set; }
    }
}
