//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSablonlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MailSablonlari()
        {
            this.MailSablonlariEkleris = new HashSet<MailSablonlariEkleri>();
        }
    
        public int MailSablonlariID { get; set; }
        public int MailSablonTipID { get; set; }
        public string SablonAdi { get; set; }
        public string Sablon { get; set; }
        public string SablonHtml { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual MailSablonTipleri MailSablonTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailSablonlariEkleri> MailSablonlariEkleris { get; set; }
    }
}
