//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menuler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menuler()
        {
            this.Rollers = new HashSet<Roller>();
        }
    
        public int MenuID { get; set; }
        public string MenuAdi { get; set; }
        public Nullable<int> BagliMenuID { get; set; }
        public string MenuIconUrl { get; set; }
        public string MenuCssClass { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<bool> DilCeviriYap { get; set; }
        public Nullable<bool> YetkisizErisim { get; set; }
        public string AuthenticationControl { get; set; }
        public Nullable<int> SiraNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roller> Rollers { get; set; }
    }
}
