//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajEkleri
    {
        public int MesajEkiID { get; set; }
        public int MesajID { get; set; }
        public string EkAdi { get; set; }
        public string EkDosyaYolu { get; set; }
    
        public virtual Mesajlar Mesajlar { get; set; }
    }
}
