//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesajlar()
        {
            this.GonderilenMaillers = new HashSet<GonderilenMailler>();
            this.MesajEkleris = new HashSet<MesajEkleri>();
            this.Mesajlar1 = new HashSet<Mesajlar>();
        }
    
        public int MesajID { get; set; }
        public Nullable<int> UstMesajID { get; set; }
        public string GroupID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public int MesajKategoriID { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Konu { get; set; }
        public string Aciklama { get; set; }
        public string AciklamaHtml { get; set; }
        public bool IsAktif { get; set; }
        public bool Silindi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailler> GonderilenMaillers { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesajEkleri> MesajEkleris { get; set; }
        public virtual MesajKategorileri MesajKategorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesajlar> Mesajlar1 { get; set; }
        public virtual Mesajlar Mesajlar2 { get; set; }
    }
}
