//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistemBilgilendirme
    {
        public int SistemBilgiID { get; set; }
        public byte BilgiTipi { get; set; }
        public string Kategori { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemYapanIP { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
