//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACokluVeriDonemleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VACokluVeriDonemleri()
        {
            this.MaddelerVeriGirisDonemleris = new HashSet<MaddelerVeriGirisDonemleri>();
            this.VASurecleriMaddeEklenenAciklamas = new HashSet<VASurecleriMaddeEklenenAciklama>();
            this.VASurecleriMaddeEklenenDosyas = new HashSet<VASurecleriMaddeEklenenDosya>();
            this.VASurecleriMaddeGirilenDegers = new HashSet<VASurecleriMaddeGirilenDeger>();
            this.VASurecleriMaddeVeriGirisDonemleris = new HashSet<VASurecleriMaddeVeriGirisDonemleri>();
        }
    
        public int VACokluVeriDonemID { get; set; }
        public string CokluVeriDonemAdi { get; set; }
        public bool IsDosyaYuklensin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaddelerVeriGirisDonemleri> MaddelerVeriGirisDonemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeEklenenAciklama> VASurecleriMaddeEklenenAciklamas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeEklenenDosya> VASurecleriMaddeEklenenDosyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeGirilenDeger> VASurecleriMaddeGirilenDegers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeVeriGirisDonemleri> VASurecleriMaddeVeriGirisDonemleris { get; set; }
    }
}
