//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriMaddeEklenenDosya
    {
        public int VASurecleriMaddeEklenenDosyaID { get; set; }
        public int VASurecleriMaddeID { get; set; }
        public int VASurecleriBirimID { get; set; }
        public Nullable<int> VACokluVeriDonemID { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaYolu { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual VACokluVeriDonemleri VACokluVeriDonemleri { get; set; }
        public virtual VASurecleriBirim VASurecleriBirim { get; set; }
        public virtual VASurecleriMadde VASurecleriMadde { get; set; }
    }
}
