//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriBirimMadde
    {
        public int VASurecleriBirimMaddeID { get; set; }
        public int VASurecleriBirimID { get; set; }
        public int VASurecleriMaddeID { get; set; }
        public Nullable<decimal> PlanlananDeger { get; set; }
        public Nullable<decimal> PlanlananDegerGelecekYil { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual VASurecleriBirim VASurecleriBirim { get; set; }
        public virtual VASurecleriMadde VASurecleriMadde { get; set; }
    }
}
