//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriMadde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VASurecleriMadde()
        {
            this.VASurecleriMaddeVeriGirisDonemleris = new HashSet<VASurecleriMaddeVeriGirisDonemleri>();
            this.VASurecleriMaddeBirims = new HashSet<VASurecleriMaddeBirim>();
            this.VASurecleriMaddeEklenenAciklamas = new HashSet<VASurecleriMaddeEklenenAciklama>();
            this.VASurecleriMaddeEklenenDosyas = new HashSet<VASurecleriMaddeEklenenDosya>();
            this.VASurecleriMaddeFormulEslesenMaddes = new HashSet<VASurecleriMaddeFormulEslesenMadde>();
            this.VASurecleriMaddeFormulEslesenMaddes1 = new HashSet<VASurecleriMaddeFormulEslesenMadde>();
            this.VASurecleriMaddeGirilenDegers = new HashSet<VASurecleriMaddeGirilenDeger>();
        }
    
        public int VASurecleriMaddeID { get; set; }
        public int VASurecID { get; set; }
        public int MaddeID { get; set; }
        public string MaddeKod { get; set; }
        public int MaddeTurID { get; set; }
        public int VeriGirisSekliID { get; set; }
        public Nullable<int> VeriTipID { get; set; }
        public string HesaplamaFormulu { get; set; }
        public int MaddeYilSonuDegerHesaplamaTipID { get; set; }
        public bool IsPlanlananDegerOlacak { get; set; }
        public bool IsPlanlananDegerOlacakGelecekYil { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Maddeler Maddeler { get; set; }
        public virtual MaddeTurleri MaddeTurleri { get; set; }
        public virtual MaddeYilSonuDegerHesaplamaTipleri MaddeYilSonuDegerHesaplamaTipleri { get; set; }
        public virtual VASurecleri VASurecleri { get; set; }
        public virtual VeriGirisSekilleri VeriGirisSekilleri { get; set; }
        public virtual VeriTipleri VeriTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeVeriGirisDonemleri> VASurecleriMaddeVeriGirisDonemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeBirim> VASurecleriMaddeBirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeEklenenAciklama> VASurecleriMaddeEklenenAciklamas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeEklenenDosya> VASurecleriMaddeEklenenDosyas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeFormulEslesenMadde> VASurecleriMaddeFormulEslesenMaddes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeFormulEslesenMadde> VASurecleriMaddeFormulEslesenMaddes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASurecleriMaddeGirilenDeger> VASurecleriMaddeGirilenDegers { get; set; }
    }
}
