//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASurecleriMaddeGirilenDeger
    {
        public int VASurecleriMaddeGirilenDegerID { get; set; }
        public int VASurecleriMaddeID { get; set; }
        public int BirimID { get; set; }
        public Nullable<int> VACokluVeriDonemID { get; set; }
        public Nullable<bool> IsVeriVar { get; set; }
        public Nullable<decimal> GirilenDeger { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public bool VeriGirisiOnaylandi { get; set; }
        public Nullable<System.DateTime> OnayIslemTarihi { get; set; }
        public Nullable<int> OnayIslemYapanID { get; set; }
        public string OnayIslemYapanIP { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual VACokluVeriDonemleri VACokluVeriDonemleri { get; set; }
        public virtual VASurecleriMadde VASurecleriMadde { get; set; }
    }
}
