//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_BirimlerTree
    {
        public string BirimTreeAdi { get; set; }
        public int BirimID { get; set; }
        public Nullable<int> UstBirimID { get; set; }
        public string BirimKod { get; set; }
        public string BirimKisaAdi { get; set; }
        public string BirimAdi { get; set; }
        public string Adres { get; set; }
        public bool IsMaddeEklenebilir { get; set; }
        public bool IsFaaliyetEklenebilir { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    }
}
