//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MaddelerTree
    {
        public string MaddeTreeAdi { get; set; }
        public int MaddeID { get; set; }
        public Nullable<int> UstMaddeID { get; set; }
        public string MaddeKod { get; set; }
        public string MaddeAdi { get; set; }
        public string Aciklama { get; set; }
        public int VeriGirisSekliID { get; set; }
        public Nullable<int> VeriTipID { get; set; }
        public string HesaplamaFormulu { get; set; }
        public bool IsAktif { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    }
}
