//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MaddeVeriGirisDurum
    {
        public int VASurecID { get; set; }
        public int Yil { get; set; }
        public int BirimID { get; set; }
        public string BirimAdi { get; set; }
        public string BirimTreeAdi { get; set; }
        public int VASurecleriMaddeID { get; set; }
        public int MaddeTurID { get; set; }
        public string MaddeTurAdi { get; set; }
        public int MaddeID { get; set; }
        public string MaddeKod { get; set; }
        public string MaddeAdi { get; set; }
        public string MaddeTreeAdi { get; set; }
        public string Aciklama { get; set; }
        public bool IsAktif { get; set; }
        public bool IsPlanlananDegerOlacak { get; set; }
        public bool IsPlanlananDegerOlacakGelecekYil { get; set; }
        public Nullable<decimal> PlanlananDeger { get; set; }
        public Nullable<decimal> PlanlananDegerGelecekYil { get; set; }
        public string YilSonuDegerHesaplamaAdi { get; set; }
        public string HesaplamaFormulu { get; set; }
        public int VeriGirisSekliID { get; set; }
        public string VeriGirisSekliAdi { get; set; }
        public Nullable<int> VeriTipID { get; set; }
        public int MaddeYilSonuDegerHesaplamaTipID { get; set; }
        public Nullable<int> GirilecekVeriSayisi { get; set; }
        public Nullable<int> GirilenVeriSayisi { get; set; }
        public Nullable<int> OnaylananVeriSayisi { get; set; }
        public Nullable<decimal> HesaplananSonucDegeri { get; set; }
    }
}
