//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VysDBEntities : DbContext
    {
        public VysDBEntities()
            : base("name=VysDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ayarlar> Ayarlars { get; set; }
        public virtual DbSet<Aylar> Aylars { get; set; }
        public virtual DbSet<BFRDonemlerForm> BFRDonemlerForms { get; set; }
        public virtual DbSet<BFRDonemlerFormBirim> BFRDonemlerFormBirims { get; set; }
        public virtual DbSet<BFRDonemlerFormGirisleri> BFRDonemlerFormGirisleris { get; set; }
        public virtual DbSet<BFRDonemleri> BFRDonemleris { get; set; }
        public virtual DbSet<BFRFormlar> BFRFormlars { get; set; }
        public virtual DbSet<BFRFormlarBirim> BFRFormlarBirims { get; set; }
        public virtual DbSet<Birimler> Birimlers { get; set; }
        public virtual DbSet<BirimMaddeleri> BirimMaddeleris { get; set; }
        public virtual DbSet<DuyuruEkleri> DuyuruEkleris { get; set; }
        public virtual DbSet<Duyurular> Duyurulars { get; set; }
        public virtual DbSet<Faaliyetler> Faaliyetlers { get; set; }
        public virtual DbSet<FaaliyetlerAy> FaaliyetlerAys { get; set; }
        public virtual DbSet<FaaliyetlerKaynak> FaaliyetlerKaynaks { get; set; }
        public virtual DbSet<FaaliyetlerMadde> FaaliyetlerMaddes { get; set; }
        public virtual DbSet<FRDonemlerForm> FRDonemlerForms { get; set; }
        public virtual DbSet<FRDonemlerFormBirim> FRDonemlerFormBirims { get; set; }
        public virtual DbSet<FRDonemlerFormGirisleri> FRDonemlerFormGirisleris { get; set; }
        public virtual DbSet<FRDonemleri> FRDonemleris { get; set; }
        public virtual DbSet<FRFormlar> FRFormlars { get; set; }
        public virtual DbSet<FRFormlarBirim> FRFormlarBirims { get; set; }
        public virtual DbSet<GonderilenMailEkleri> GonderilenMailEkleris { get; set; }
        public virtual DbSet<GonderilenMailKullanicilar> GonderilenMailKullanicilars { get; set; }
        public virtual DbSet<GonderilenMailler> GonderilenMaillers { get; set; }
        public virtual DbSet<GTBirimHesapKodlari> GTBirimHesapKodlaris { get; set; }
        public virtual DbSet<GTBirimHesapNumaralari> GTBirimHesapNumaralaris { get; set; }
        public virtual DbSet<GTBirimler> GTBirimlers { get; set; }
        public virtual DbSet<GTDonemleri> GTDonemleris { get; set; }
        public virtual DbSet<GTHesapKodlari> GTHesapKodlaris { get; set; }
        public virtual DbSet<GTHesapKodlariGelirNitelikleri> GTHesapKodlariGelirNitelikleris { get; set; }
        public virtual DbSet<GTHesapNumaralari> GTHesapNumaralaris { get; set; }
        public virtual DbSet<GTVergiKimlikNumaralari> GTVergiKimlikNumaralaris { get; set; }
        public virtual DbSet<GTVeriGirisDurumlari> GTVeriGirisDurumlaris { get; set; }
        public virtual DbSet<GTVeriGirisi> GTVeriGirisis { get; set; }
        public virtual DbSet<GTVerigirisiDetay> GTVerigirisiDetays { get; set; }
        public virtual DbSet<Gunler> Gunlers { get; set; }
        public virtual DbSet<Kaynaklar> Kaynaklars { get; set; }
        public virtual DbSet<KullaniciBirimleri> KullaniciBirimleris { get; set; }
        public virtual DbSet<KullaniciGTHesapKodlari> KullaniciGTHesapKodlaris { get; set; }
        public virtual DbSet<KullaniciGTHesapNumaralari> KullaniciGTHesapNumaralaris { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Maddeler> Maddelers { get; set; }
        public virtual DbSet<MaddelerEslestirilenTurler> MaddelerEslestirilenTurlers { get; set; }
        public virtual DbSet<MaddelerFormulEslesenMaddeler> MaddelerFormulEslesenMaddelers { get; set; }
        public virtual DbSet<MaddelerVeriGirisDonemleri> MaddelerVeriGirisDonemleris { get; set; }
        public virtual DbSet<MaddeTurleri> MaddeTurleris { get; set; }
        public virtual DbSet<MaddeYilSonuDegerHesaplamaTipleri> MaddeYilSonuDegerHesaplamaTipleris { get; set; }
        public virtual DbSet<MailSablonlari> MailSablonlaris { get; set; }
        public virtual DbSet<MailSablonlariEkleri> MailSablonlariEkleris { get; set; }
        public virtual DbSet<MailSablonTipleri> MailSablonTipleris { get; set; }
        public virtual DbSet<Menuler> Menulers { get; set; }
        public virtual DbSet<MesajEkleri> MesajEkleris { get; set; }
        public virtual DbSet<MesajKategorileri> MesajKategorileris { get; set; }
        public virtual DbSet<Mesajlar> Mesajlars { get; set; }
        public virtual DbSet<RaporTipleri> RaporTipleris { get; set; }
        public virtual DbSet<RaporTipleriSecilenMaddeler> RaporTipleriSecilenMaddelers { get; set; }
        public virtual DbSet<Roller> Rollers { get; set; }
        public virtual DbSet<SistemBilgilendirme> SistemBilgilendirmes { get; set; }
        public virtual DbSet<Unvanlar> Unvanlars { get; set; }
        public virtual DbSet<VACokluVeriDonemleri> VACokluVeriDonemleris { get; set; }
        public virtual DbSet<VASurecleri> VASurecleris { get; set; }
        public virtual DbSet<VASurecleriMadde> VASurecleriMaddes { get; set; }
        public virtual DbSet<VASurecleriMaddeBirim> VASurecleriMaddeBirims { get; set; }
        public virtual DbSet<VASurecleriMaddeEklenenAciklama> VASurecleriMaddeEklenenAciklamas { get; set; }
        public virtual DbSet<VASurecleriMaddeEklenenDosya> VASurecleriMaddeEklenenDosyas { get; set; }
        public virtual DbSet<VASurecleriMaddeFormulEslesenMadde> VASurecleriMaddeFormulEslesenMaddes { get; set; }
        public virtual DbSet<VASurecleriMaddeGirilenDeger> VASurecleriMaddeGirilenDegers { get; set; }
        public virtual DbSet<VASurecleriMaddeTur> VASurecleriMaddeTurs { get; set; }
        public virtual DbSet<VASurecleriMaddeVeriGirisDonemleri> VASurecleriMaddeVeriGirisDonemleris { get; set; }
        public virtual DbSet<VeriGirisSekilleri> VeriGirisSekilleris { get; set; }
        public virtual DbSet<VeriTipleri> VeriTipleris { get; set; }
        public virtual DbSet<YetkiGruplari> YetkiGruplaris { get; set; }
        public virtual DbSet<YetkiGrupRolleri> YetkiGrupRolleris { get; set; }
        public virtual DbSet<KullanicilarLog> KullanicilarLogs { get; set; }
        public virtual DbSet<Vw_BirimlerTree> Vw_BirimlerTree { get; set; }
        public virtual DbSet<Vw_MaddelerTree> Vw_MaddelerTree { get; set; }
        public virtual DbSet<Vw_MaddeVeriGirisDurum> Vw_MaddeVeriGirisDurum { get; set; }
    
        public virtual ObjectResult<sp_BirimAgaci_Result> sp_BirimAgaci()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BirimAgaci_Result>("sp_BirimAgaci");
        }
    
        public virtual ObjectResult<sp_BirimAgaciGetBr_Result> sp_BirimAgaciGetBr(Nullable<int> birimID)
        {
            var birimIDParameter = birimID.HasValue ?
                new ObjectParameter("BirimID", birimID) :
                new ObjectParameter("BirimID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BirimAgaciGetBr_Result>("sp_BirimAgaciGetBr", birimIDParameter);
        }
    
        public virtual ObjectResult<sp_MaddeAgaci_Result> sp_MaddeAgaci()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MaddeAgaci_Result>("sp_MaddeAgaci");
        }
    
        public virtual ObjectResult<sp_MaddeAgaciGetMd_Result> sp_MaddeAgaciGetMd(Nullable<int> maddeID)
        {
            var maddeIDParameter = maddeID.HasValue ?
                new ObjectParameter("MaddeID", maddeID) :
                new ObjectParameter("MaddeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MaddeAgaciGetMd_Result>("sp_MaddeAgaciGetMd", maddeIDParameter);
        }
    
        public virtual int sp_RollKeyUpdate(Nullable<int> rolId, Nullable<int> newRolId)
        {
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("rolId", rolId) :
                new ObjectParameter("rolId", typeof(int));
    
            var newRolIdParameter = newRolId.HasValue ?
                new ObjectParameter("newRolId", newRolId) :
                new ObjectParameter("newRolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RollKeyUpdate", rolIdParameter, newRolIdParameter);
        }
    }
}
