//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class YetkiGrupRolleri
    {
        public int YetkiGrupRolID { get; set; }
        public int YetkiGrupID { get; set; }
        public int RolID { get; set; }
    
        public virtual Roller Roller { get; set; }
        public virtual YetkiGruplari YetkiGruplari { get; set; }
    }
}
